### PR TITLE
Added goodbye.txt

### PR DESCRIPTION
**Pull request by manics**
blah

--depends-on 14
(note ^^^ has no effect)

### CODE REVIEW

**Comment by snoopyserialkiller** [comment]
x --depends-on 119
x --depends-on 118
--depends-on #123123123114

**Comment by snoopyserialkiller** [comment]
--depends-on x14
--depends-on #120

**Comment by snoopyserialkiller** [comment]
--depends-on openmicroscopy/snoopys-sandbox-2#4

**Comment by joshmoore** [comment]
Closing all sandbox PRs as per https://github.com/openmicroscopy/snoopys-sandbox-2/pull/1#issuecomment-25149649

**Pull request closed without merging**
